/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package treasurehauntadventure;

import javax.swing.JOptionPane;

/**
 *
 * @author ervas
 */
public class Menu extends javax.swing.JFrame {

    /**
     * Creates new form Menu
     */
    public Menu() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        score = new javax.swing.JLabel();
        startgame = new javax.swing.JLabel();
        start = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("MENU");

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        score.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        score.setText("SCOREBOARD");
        score.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        score.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                scoreMouseClicked(evt);
            }
        });
        jPanel1.add(score, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 270, 160, 70));

        startgame.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        startgame.setText("START GAME");
        startgame.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        startgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                startgameMouseClicked(evt);
            }
        });
        jPanel1.add(startgame, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 290, -1, -1));

        start.setIcon(new javax.swing.ImageIcon(getClass().getResource("/treasurehauntadventure/WhatsApp Image 2025-04-30 at 15.11.32.jpeg"))); // NOI18N
        jPanel1.add(start, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 835, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 480, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void scoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_scoreMouseClicked
        // TODO add your handling code here:
        
        Scoreboard ScoreboardFrame = new Scoreboard();
        ScoreboardFrame.setVisible(true);
        ScoreboardFrame.pack();
        ScoreboardFrame.setLocationRelativeTo(null);
        this.dispose();
        
       
    }//GEN-LAST:event_scoreMouseClicked

    private void startgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_startgameMouseClicked
        // TODO add your handling code here:
        
      String username = JOptionPane.showInputDialog(this, "Enter your username:");
       if (username != null && !username.trim().isEmpty()) {
        
        Level1 Level1Frame = new Level1(username,1);  // Yeni oyun ekranı açılıyor
        Level1Frame.setVisible(true);
        Level1Frame.pack();
        Level1Frame.setLocationRelativeTo(null);
        this.dispose();
        
    } else {
        JOptionPane.showMessageDialog(this, "Username cannot be empty!");
    }
        
        
    }//GEN-LAST:event_startgameMouseClicked

    /**
     * @param args the command line arguments
     */
   public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
            }
        });
    }


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel score;
    private javax.swing.JLabel start;
    private javax.swing.JLabel startgame;
    // End of variables declaration//GEN-END:variables
}
